version: 2
jobs:
  build:
    working_directory: ~/MMM-IOTStatus
    docker: 
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: eslint
          command: npm run eslint
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/MMM-IOTStatus
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/MMM-IOTStatus/.npmrc
      - run:
          name: Publish package
          command: npm publish